# Generated by Django 2.0.7 on 2018-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Loved'),
        ),
    ]
